#!/usr/bin/ruby
# -*- coding: utf-8 -*-
#
# csi - Common SQL Interface
#
# Author: kaieu
#

RUBY_VERSION >= '2.0.0' or abort "#$0: ruby 2.0.0 or higher required."

require 'pathname'

$LOAD_PATH << Pathname(__FILE__).realpath.parent + "lib"
require 'csi'

Csi.main ARGV

# vim:set ts=2 sw=2 et ft=ruby:
